modalities: 

    inputs:
        AERIAL_RGBI       : True
        AERIAL-RLT_PAN    : False
        DEM_ELEV          : False
        SPOT_RGBI         : False
        SENTINEL2_TS      : True 
        SENTINEL1-ASC_TS  : True
        SENTINEL1-DESC_TS : True
        
    inputs_channels:
        AERIAL_RGBI       : [4,1,2] #[1,2,3,4]
        SPOT_RGBI         : [1,2,3]
        SENTINEL2_TS      : [1,2,3,4,5,6,7,8,9,10]
        SENTINEL1-ASC_TS  : [1,2] 
        SENTINEL1-DESC_TS : [1,2]

    aux_loss: 
        AERIAL_RGBI       : False
        AERIAL-RLT_PAN    : False
        DEM_ELEV          : False
        SPOT_RGBI         : False
        SENTINEL2_TS      : False
        SENTINEL1-ASC_TS  : False
        SENTINEL1-DESC_TS : False

    aux_loss_weight: 1.5 # multiplier before adding to main loss

    modality_dropout: # between 0 (no dropout) and 1 (complete systematic dropout)
        AERIAL_RGBI       : 0
        AERIAL-RLT_PAN    : 0
        DEM_ELEV          : 0
        SPOT_RGBI         : 0
        SENTINEL2_TS      : 0
        SENTINEL1-ASC_TS  : 0
        SENTINEL1-DESC_TS : 0

    pre_processings: 
        filter_sentinel2: True 
        filter_sentinel2_max_cloud : 1 # [0-100]
        filter_sentinel2_max_snow : 1 # [0-100]
        filter_sentinel2_max_frac_cover : 0.05 # [0-1]
        temporal_average_sentinel2 : False  # possible : False, monthly, semi-monthly
        temporal_average_sentinel1 : False

        calc_elevation : True
        calc_elevation_stack_dsm : True 
        
        use_augmentation: False

    normalization: 
        norm_type : custom   # possible :  custom, scaling, without

        AERIAL_RGBI_means : [105.66, 111.35, 102.18]  #[105.66, 111.35, 102.18, 106.59]
        AERIAL_RGBI_stds  : [52.23, 45.62, 44.30] #[52.23, 45.62, 44.29, 39.78]

        AERIAL-RLT_PAN_means : [125.92]
        AERIAL-RLT_PAN_stds  : [38.45]

        SPOT_RGBI_means : [433.26, 508.75, 467.77, 1137.03]
        SPOT_RGBI_stds  : [312.76, 284.61, 226.02, 543.11]

        DEM_ELEV_means : [311.06, 311.06] # use same for both DSM/DTM to allow keeping differences of elevation
        DEM_ELEV_stds  : [537.55, 537.55] # use same for both DSM/DTM to allow keeping differences of elevation
