paths :   

    out_folder: 'C:/Users/agari/Desktop/DEVS-FLAIR-INC/results/'
    out_model_name: 'TEST_FUSION'
    train_csv: 'C:/Users/agari/Desktop/DEVS-FLAIR-INC/data/split_csv/toy/TRAIN_FLAIR-INC_TOY.csv'
    val_csv: 'C:/Users/agari/Desktop/DEVS-FLAIR-INC/data/split_csv/toy/VALID_FLAIR-INC_TOY.csv'
    test_csv: 'C:/Users/agari/Desktop/DEVS-FLAIR-INC/data/split_csv/toy/TEST_FLAIR-INC_TOY.csv'
    global_mtd_folder: 'C:/Users/agari/Desktop/DEVS-FLAIR-INC/data/FLAIR-INC_TOY/GLOBAL_ALL_MTD/'
    ckpt_model_path: ''
    path_metadata_aerial: '../flair_aerial_metadata.json'


tasks: 

    train: True
    train_tasks: 
        init_weights_only_from_ckpt: False
        resume_training_from_ckpt: False

    predict: True
    write_files: True
    georeferencing_output: True


modalities:

    inputs:
        AERIAL_RGBI      : False
        AERIAL-RLT_PAN   : False
        DEM_ELEV         : False
        SPOT_RGBI        : False
        SENTINEL2_TS     : True 
        SENTINEL1-ASC_TS : False
        SENTINEL1-DESC_TS: False
        
    labels : 'AERIAL_LABEL-COSIA'

    inputs_channels:
        aerial    : [1,2,3,4]
        spot      : [1,2,3]
        sentinel2 : [1,2,3,4,5,6,7,8,9,10]
        sentinel1 : [1,2] 

    aux_loss: 
        AERIAL_RGBI      : False
        AERIAL-RLT_PAN   : False
        DEM_ELEV         : False
        SPOT_RGBI        : False
        SENTINEL2_TS     : False
        SENTINEL1-ASC_TS : False
        SENTINEL1-DESC_TS: False
    
    aux_loss_weight: 1.5


    modality_dropout:
        AERIAL_RGBI      : 0.1
        AERIAL-RLT_PAN   : 0
        DEM_ELEV         : 0.1
        SPOT_RGBI        : 0.1
        SENTINEL2_TS     : 0.1
        SENTINEL1-ASC_TS : 0.1
        SENTINEL1-DESC_TS: 0.1


    pre_processings: 
        filter_sentinel2: True 
        filter_sentinel2_max_cloud : 1 # [0-100]
        filter_sentinel2_max_snow : 1 # [0-100]
        filter_sentinel2_max_frac_cover : 0.05 # [0-1]
        temporal_average_sentinel2 : False  # possible : False, monthly, semi-monthly
        temporal_average_sentinel1 : False
        calc_elevation : False
        use_augmentation: False
        use_metadata: False   

    normalization: 
        norm_type : custom   # possible :  custom, scaling, without

        aerial_means : [105.66, 111.35, 102.18, 106.59]
        aerial_stds  : [52.23, 45.62, 44.29, 39.78]

        aerial_rlt_means : [125.92]
        aerial_rlt_stds  : [38.45]

        spot_means : [433.26, 508.75, 467.77, 1137.03]
        spot_stds  : [312.76, 284.61, 226.02, 543.11]

        elev_means : [311.06, 311.06] # use same for both DSM/DTM to allow keeping differences of elevation
        elev_stds  : [537.55, 537.55]


models:
    
    monotemp_model: 
        #arch: 'hf_openmmlab/upernet-swin-small' 
        arch: 'smp_resnet34-unet' 

        new_channels_init_mode: 'copy_third' # possible :  copy_first, copy_second, copy_third, random

    multitemp_model: 
        ref_date: '05-15' # defined for whole dataset    
        encoder_widths: [64, 64, 64, 128] # last must be equivalent to decoder_widths
        decoder_widths: [32, 32, 64, 128] # last must be equivalent to encoder_widths
        out_conv: [32, 19]
        str_conv_k: 3
        str_conv_s: 1
        str_conv_p: 1
        agg_mode: "att_group"
        encoder_norm: "group"
        n_head: 16
        d_model: 256
        d_k: 4
        encoder: False
        return_maps: True
        pad_value: 0
        padding_mode: "reflect"

classes: 

    0  :   [1, 'building']
    1  :   [1, 'greenhouse']
    2  :   [1, 'swimming_pool']
    3  :   [1, 'impervious surface']
    4  :   [1, 'pervious surface']
    5  :   [1, 'bare soil']
    6  :   [1, 'water']
    7  :   [1, 'snow']
    8  :   [1, 'herbaceous vegetation']
    9  :   [1, 'agricultural land']
    10 :   [1, 'plowed land']
    11 :   [1, 'vineyard']
    12 :   [1, 'deciduous']
    13 :   [1, 'coniferous']
    14 :   [1, 'brushwood']
    15 :   [0, 'clear cut']
    16 :   [0, 'ligneous']
    17 :   [0, 'mixed']
    18 :   [0, 'undefined']


hyperparams:

    num_epochs: 2
    batch_size: 2
    seed: 2022
    learning_rate: 0.02
    use_class_weights: True

    accelerator: 'gpu'
    num_nodes: 1
    gpus_per_node: 1
    strategy: 'auto'
    num_workers: 0

saving:   

    codecarbon: False
    
    ckpt_save_also_last: True
    ckpt_verbose: False
    ckpt_weights_only: False
    ckpt_monitor: 'val_loss'
    ckpt_monitor_mode: 'min'
    ckpt_earlystopping_patience: 30
    cp_csv_and_conf_to_output: True
    enable_progress_bar: True
    progress_rate: 10
