modalities: 

    inputs:
        AERIAL_RGBI      : True
        AERIAL-RLT_PAN   : False
        DEM_ELEV         : False
        SPOT_RGBI        : False
        SENTINEL2_TS     : True 
        SENTINEL1-ASC_TS : False
        SENTINEL1-DESC_TS: False
        

    inputs_channels:
        aerial    : [1,2,3,4]
        spot      : [1,2,3]
        sentinel2 : [1,2,3,4,5,6,7,8,9,10]
        sentinel1 : [1,2] 

    aux_loss: 
        AERIAL_RGBI      : False
        AERIAL-RLT_PAN   : False
        DEM_ELEV         : False
        SPOT_RGBI        : False
        SENTINEL2_TS     : False
        SENTINEL1-ASC_TS : False
        SENTINEL1-DESC_TS: False

    aux_loss_weight: 1.5


    modality_dropout:
        AERIAL_RGBI      : 0
        AERIAL-RLT_PAN   : 0
        DEM_ELEV         : 0
        SPOT_RGBI        : 0
        SENTINEL2_TS     : 0
        SENTINEL1-ASC_TS : 0
        SENTINEL1-DESC_TS: 0


    pre_processings: 
        filter_sentinel2: True 
        filter_sentinel2_max_cloud : 1 # [0-100]
        filter_sentinel2_max_snow : 1 # [0-100]
        filter_sentinel2_max_frac_cover : 0.05 # [0-1]
        temporal_average_sentinel2 : False  # possible : False, monthly, semi-monthly
        temporal_average_sentinel1 : False
        calc_elevation : False
        use_augmentation: False
        use_metadata: False   


    normalization: 
        norm_type : custom   # possible :  custom, scaling, without

        aerial_means : [105.66, 111.35, 102.18, 106.59]
        aerial_stds  : [52.23, 45.62, 44.29, 39.78]

        aerial_rlt_means : [125.92]
        aerial_rlt_stds  : [38.45]

        spot_means : [433.26, 508.75, 467.77, 1137.03]
        spot_stds  : [312.76, 284.61, 226.02, 543.11]

        elev_means : [311.06, 311.06] # use same for both DSM/DTM to allow keeping differences of elevation
        elev_stds  : [537.55, 537.55]


