models: 

    monotemp_model: 
        #arch: 'hf_openmmlab/upernet-swin-small' 
        arch: 'smp_resnet34-unet' 

        new_channels_init_mode: 'random' # possible :  copy_first, copy_second, copy_third, random

    multitemp_model: 
        ref_date: '05-15' # defined for whole dataset    
        encoder_widths: [64, 64, 64, 128] # last must be equivalent to decoder_widths
        decoder_widths: [32, 32, 64, 128] # last must be equivalent to encoder_widths
        out_conv: [32, 19]
        str_conv_k: 3
        str_conv_s: 1
        str_conv_p: 1
        agg_mode: "att_group"
        encoder_norm: "group"
        n_head: 16
        d_model: 256
        d_k: 4
        encoder: False
        return_maps: True
        pad_value: 0
        padding_mode: "reflect"