labels: 
  - AERIAL_LABEL-COSIA

labels_configs:
    AERIAL_LABEL-COSIA:
        value_name:
            0  : 'building'
            1  : 'greenhouse'
            2  : 'swimming_pool'
            3  : 'impervious surface'
            4  : 'pervious surface'
            5  : 'bare soil'
            6  : 'water'
            7  : 'snow'
            8  : 'herbaceous vegetation'
            9  : 'agricultural land'
            10 : 'plowed land'
            11 : 'vineyard'
            12 : 'deciduous'
            13 : 'coniferous'
            14 : 'brushwood'
            15 : 'clear cut'
            16 : 'ligneous'
            17 : 'mixed'
            18 : 'undefined'
        value_weights: 
            default: 1
            default_exceptions:
                15: 0
                16: 0
                17: 0
                18: 0
            per_modality_exceptions:
                SENTINEL2_TS: 
                    10: 0
                SENTINEL1-ASC_TS: 
                    1: 0
                SENTINEL1-DESC_TS:
                    3: 0

    LPIS:
        value_name:
            0  : 'to_define'   
            1  : 'to_define'
            2  : 'to_define'
            3  : 'to_define'
            4  : 'to_define'
            5  : 'to_define'
            6  : 'to_define'
            7  : 'to_define'
            8  : 'to_define'
            9  : 'to_define'
            10 : 'to_define'
            11 : 'to_define'
            12 : 'to_define'
            13 : 'to_define'
            14 : 'to_define'
            15 : 'to_define'
            16 : 'to_define'
            17 : 'to_define'
            18 : 'to_define'
            19 : 'to_define'
            20 : 'to_define'
            21 : 'to_define'
            22 : 'to_define'
            23 : 'to_define'
            24 : 'to_define'
            25 : 'to_define'
            26 : 'to_define'
            27 : 'to_define'
            28 : 'to_define'
            29 : 'to_define'
            30 : 'to_define'
            31 : 'to_define'
            32 : 'to_define'
            33 : 'to_define'
            34 : 'to_define'
            35 : 'to_define'
            36 : 'to_define'
            37 : 'to_define'
            38 : 'to_define'
            39 : 'to_define'
            40 : 'to_define'
            41 : 'to_define'
            42 : 'to_define'
            43 : 'to_define'
            44 : 'to_define'
            45 : 'to_define'
            46 : 'to_define'
            47 : 'to_define'
            48 : 'to_define'
            49 : 'to_define'
            50 : 'to_define'
            51 : 'to_define'
            52 : 'to_define'
            53 : 'to_define'
            54 : 'to_define'
            55 : 'to_define'
            56 : 'to_define'
            57 : 'to_define'
            58 : 'to_define'
            59 : 'to_define'
            60 : 'to_define'
            61 : 'to_define'
            62 : 'to_define'
            63 : 'to_define'
            64 : 'to_define'
            65 : 'to_define'
            66 : 'to_define'
            67 : 'to_define'
            68 : 'to_define'
            69 : 'to_define'
            70 : 'to_define'
            71 : 'to_define'
            72 : 'to_define'
        value_weights: 
            default: 1
            default_exceptions:
                0: 0
                25: 0
                55: 0
            per_modality_exceptions:
                SENTINEL2_TS: 
                    27: 0
                SENTINEL1-ASC_TS: 
                    27: 0
                SENTINEL1-DESC_TS:
                    27: 0
