labels: 
  - AERIAL_LABEL-COSIA
  - ALL_LABEL-LPIS

labels_configs:
    AERIAL_LABEL-COSIA:
        task_weight: 1
        value_name:
            0  : 'building'
            1  : 'greenhouse'
            2  : 'swimming_pool'
            3  : 'impervious surface'
            4  : 'pervious surface'
            5  : 'bare soil'
            6  : 'water'
            7  : 'snow'
            8  : 'herbaceous vegetation'
            9  : 'agricultural land'
            10 : 'plowed land'
            11 : 'vineyard'
            12 : 'deciduous'
            13 : 'coniferous'
            14 : 'brushwood'
            15 : 'clear cut'
            16 : 'ligneous'
            17 : 'mixed'
            18 : 'undefined'
        value_weights: 
            default: 1
            default_exceptions:
                15: 0
                16: 0
                17: 0
                18: 0
            per_modality_exceptions:
                AERIAL_RGBI: 
                #    10: 0
                SENTINEL2_TS: 
                SENTINEL1-ASC_TS: 
                SENTINEL1-DESC_TS:

    ALL_LABEL-LPIS:
        task_weight: 1
        label_channel_nomenclature: 1
        value_name2:
            0  : 'grasses monoculture'   
            1  : 'grasses mixture'
            2  : 'winter wheat'
            3  : 'spring wheat'
            4  : 'winter barley'
            5  : 'spring barley'
            6  : 'maize'
            7  : 'sorghum'
            8  : 'millet/foxtail millet'
            9  : 'winter durum wheat'
            10 : 'winter triticale'
            11 : 'winter oat'
            12 : 'winter rye'
            13 : 'sprint oat'
            14 : 'other spring cereal'
            15 : 'other cereals'
            16 : 'rice'
            17 : 'hemp/tobacco'
            18 : 'fiber flax'
            19 : 'other flax'
            20 : 'sunflower'
            21 : 'rapeseed'
            22 : 'mustard'
            23 : 'other oilseed crops'
            24 : 'soy'
            25 : 'spring peas'
            26 : 'winter protein crops'
            27 : 'other protein crops'
            28 : 'alfalfa'
            29 : 'clove'
            30 : 'other fodder legumes'
            31 : 'beetroots'
            32 : 'potatoes'
            33 : 'fruits and vegetables'
            34 : 'aromatic/medicinal plants'
            35 : 'buckwheat'
            36 : 'other arable crops'
            37 : 'vineyard'
            38 : 'olive groves'
            39 : 'fruit orchards'
            40 : 'nut orchards'
            41 : 'lavandin'
            42 : 'berries'
            43 : 'other permanent crops'
            44 : 'mixed crops'
            45 : 'background'
        value_name:
            0  : 'grasses'   
            1  : 'wheat'
            2  : 'barley'
            3  : 'maize'
            4  : 'other cereals'
            5  : 'rice'
            6  : 'flax/hemp/tobacco'
            7  : 'sunflower'
            8  : 'rapeseed'
            9  : 'other oilseed crops'
            10 : 'soy'
            11 : 'other protein crops'
            12 : 'fodder legumes'
            13 : 'beetroots'
            14 : 'potatoes'
            15 : 'other arable crops'
            16 : 'vineyard'
            17 : 'olive groves'
            18 : 'fruits orchards'
            19 : 'nut orchards'
            20 : 'other permanent crops'
            21 : 'mixed crops'
            22 : 'background'

        value_weights: 
            default: 1
            default_exceptions:
            per_modality_exceptions:
                SENTINEL2_TS: 
                SENTINEL1-ASC_TS: 
                SENTINEL1-DESC_TS:
